import { createHash } from 'node:crypto';
import { readFile, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import type { ToolAdapter, Violation } from '@retemper/lodestar-types';

/**
 * A single extends entry.
 * - `string` — static config (exports an array)
 * - `{ specifier: string; factory: true }` — factory config (exports `(rootDir) => Config[]`)
 */
type ExtendsEntry = string | { readonly specifier: string; readonly factory: true };

/** ESLint-specific adapter configuration */
interface EslintAdapterConfig {
  /** Base presets — 'recommended', 'strict', 'stylistic' map to typescript-eslint configs */
  readonly presets?: readonly string[];
  /** ESLint plugin packages to include (e.g., import-x, unicorn) */
  readonly plugins?: Readonly<Record<string, unknown>>;
  /** ESLint rules with standard severity/options format */
  readonly rules?: Readonly<Record<string, unknown>>;
  /** Global ignore patterns */
  readonly ignores?: readonly string[];
  /** File-specific rule overrides */
  readonly overrides?: readonly {
    readonly files: readonly string[];
    readonly rules: Readonly<Record<string, unknown>>;
  }[];

  /**
   * External ESLint flat config(s) to extend.
   * Module specifier string(s) — packages that export a config array or factory function.
   *
   * @example
   * // Static config (exports array)
   * extends: '@repo/eslint-config/nest-eslint.config.js'
   *
   * // Factory config (exports (rootDir) => Config[])
   * extends: { specifier: '@repo/eslint-config/react-app.config.js', factory: true }
   *
   * // Multiple configs
   * extends: [
   *   '@repo/eslint-config/base.config.js',
   *   { specifier: '@repo/eslint-config/react-app.config.js', factory: true },
   * ]
   */
  readonly extends?: ExtendsEntry | readonly ExtendsEntry[];

  /**
   * Module system for the generated eslint.config.js.
   * - `'esm'` — ES module syntax (import/export)
   * - `'cjs'` — CommonJS syntax (require/module.exports)
   * - `'auto'` — detect from package.json "type" field (default)
   *
   * @default 'auto'
   */
  readonly moduleFormat?: 'esm' | 'cjs' | 'auto';
}

/** Generated file header with content hash for drift detection */
const GENERATED_HEADER = '// @generated by Lodestar ESLint adapter — do not edit';

/** Hash marker prefix used in generated files */
const HASH_PREFIX = '// @lodestar-hash ';

/** Map of preset names to typescript-eslint config paths */
const PRESET_MAP: Readonly<Record<string, { module: string; export: string }>> = {
  recommended: { module: 'typescript-eslint', export: 'configs.recommended' },
  strict: { module: 'typescript-eslint', export: 'configs.strict' },
  stylistic: { module: 'typescript-eslint', export: 'configs.stylistic' },
};

/** Dynamically import a default export */
async function importDefault(moduleName: string): Promise<unknown> {
  try {
    const mod = await import(moduleName);
    return mod.default ?? mod;
  } catch {
    return null;
  }
}

/** Resolve preset names to actual ESLint config objects */
async function resolvePresets(presets: readonly string[]): Promise<unknown[]> {
  const configs: unknown[] = [];

  for (const preset of presets) {
    const mapping = PRESET_MAP[preset];
    if (!mapping) continue;

    const mod = await importDefault(mapping.module);
    if (!mod || typeof mod !== 'object') continue;

    const parts = mapping.export.split('.');
    let value: unknown = mod;
    for (const part of parts) {
      value = (value as Record<string, unknown>)?.[part];
    }

    if (Array.isArray(value)) {
      configs.push(...value);
    } else if (value) {
      configs.push(value);
    }
  }

  return configs;
}

/**
 * Resolve `extends` entries into concrete flat-config blocks.
 * Mirrors the resolution that `generateConfigFile()` encodes into its output:
 *   - static entries spread the imported array
 *   - factory entries are invoked with `rootDir`
 */
async function resolveExtends(
  ext: EslintAdapterConfig['extends'],
  rootDir: string | undefined,
): Promise<unknown[]> {
  const entries = normalizeExtends(ext);
  if (entries.length === 0) return [];

  const configs: unknown[] = [];
  for (const entry of entries) {
    const { specifier, factory } = parseExtendsEntry(entry);
    const mod = await importDefault(specifier);
    if (mod === null) {
      throw new Error(
        `Failed to load ESLint config from '${specifier}'. ` +
          'Ensure the package is installed and resolvable from the target directory.',
      );
    }

    let resolved: unknown;
    if (factory) {
      if (typeof mod !== 'function') {
        throw new Error(
          `\`extends\` entry '${specifier}' was declared as a factory but does not export a function.`,
        );
      }
      if (!rootDir) {
        throw new Error(
          `\`extends\` factory entry '${specifier}' requires a rootDir but none was provided.`,
        );
      }
      resolved = (mod as (dir: string) => unknown)(rootDir);
    } else {
      resolved = mod;
    }

    if (Array.isArray(resolved)) {
      configs.push(...resolved);
    } else if (resolved) {
      configs.push(resolved);
    }
  }

  return configs;
}

/**
 * Build ESLint flat config array from adapter config.
 * @param adapterConfig - the ESLint adapter configuration
 * @param rootDir - the package root; required when `extends` includes factory entries
 */
async function buildFlatConfig(
  adapterConfig: EslintAdapterConfig,
  rootDir?: string,
): Promise<unknown[]> {
  const configs: unknown[] = [];

  if (adapterConfig.ignores && adapterConfig.ignores.length > 0) {
    configs.push({ ignores: [...adapterConfig.ignores] });
  }

  const hasExtends =
    adapterConfig.extends !== undefined && normalizeExtends(adapterConfig.extends).length > 0;

  if (hasExtends) {
    // When the user provides `extends`, delegate baseline rule choice to the shared config.
    // Mirrors `generateConfigFile()`, which never emits @eslint/js recommended in that case.
    const extendsConfigs = await resolveExtends(adapterConfig.extends, rootDir);
    configs.push(...extendsConfigs);
  } else {
    const baseEslint = await importDefault('@eslint/js');
    const recommended = (baseEslint as { configs?: { recommended?: unknown } })?.configs
      ?.recommended;
    if (recommended) {
      configs.push(recommended);
    }
  }

  if (adapterConfig.presets) {
    const presetConfigs = await resolvePresets(adapterConfig.presets);
    configs.push(...presetConfigs);
  }

  const mainConfig: Record<string, unknown> = {};
  if (adapterConfig.plugins && Object.keys(adapterConfig.plugins).length > 0) {
    mainConfig.plugins = { ...adapterConfig.plugins };
  }
  if (adapterConfig.rules && Object.keys(adapterConfig.rules).length > 0) {
    mainConfig.rules = { ...adapterConfig.rules };
  }
  if (Object.keys(mainConfig).length > 0) {
    configs.push(mainConfig);
  }

  if (adapterConfig.overrides) {
    for (const override of adapterConfig.overrides) {
      configs.push({
        files: [...override.files],
        rules: { ...override.rules },
      });
    }
  }

  return configs;
}

/** Normalize extends option to array */
function normalizeExtends(
  ext: EslintAdapterConfig['extends'],
): readonly ExtendsEntry[] {
  if (!ext) return [];
  if (typeof ext === 'string' || ('specifier' in ext && !Array.isArray(ext))) {
    return [ext];
  }
  return ext;
}

/** Parse an extends entry into specifier and factory flag */
function parseExtendsEntry(entry: ExtendsEntry): { specifier: string; factory: boolean } {
  if (typeof entry === 'string') {
    return { specifier: entry, factory: false };
  }
  return { specifier: entry.specifier, factory: entry.factory };
}

/** Detect module system from package.json in the given directory */
async function detectModuleSystem(rootDir: string): Promise<'esm' | 'cjs'> {
  try {
    const pkg = JSON.parse(await readFile(join(rootDir, 'package.json'), 'utf-8')) as {
      type?: string;
    };
    return pkg.type === 'module' ? 'esm' : 'cjs';
  } catch {
    return 'cjs';
  }
}

/** Resolve the effective module system for code generation */
async function resolveModuleSystem(
  config: EslintAdapterConfig,
  rootDir: string,
): Promise<'esm' | 'cjs'> {
  const explicit = config.moduleFormat ?? 'auto';
  if (explicit !== 'auto') return explicit;
  return detectModuleSystem(rootDir);
}

/** Serialize a value to inline JavaScript (JSON with unquoted keys for simple cases) */
function toInlineJs(value: unknown): string {
  return JSON.stringify(value, null, 2);
}

/**
 * Generate static eslint.config.js source code from adapter config.
 * Produces a self-contained file that does not depend on lodestar at runtime.
 *
 * When `extends` is set, `rules` are inlined as an additional config object.
 * `presets` and `plugins` require dynamic imports and cannot be statically generated
 * alongside `extends` — use them in the shared config package instead.
 */
async function generateConfigFile(config: EslintAdapterConfig, rootDir: string): Promise<string> {
  if (config.extends && config.presets?.length) {
    throw new Error(
      'Cannot use `presets` with `extends` in static code generation. ' +
        'Move presets into the shared config package referenced by `extends`.',
    );
  }
  if (config.extends && config.plugins && Object.keys(config.plugins).length > 0) {
    throw new Error(
      'Cannot use `plugins` with `extends` in static code generation. ' +
        'Move plugins into the shared config package referenced by `extends`.',
    );
  }
  const mod = await resolveModuleSystem(config, rootDir);
  const entries = config.extends ? normalizeExtends(config.extends) : [];
  const hasFactory = entries.some((e) => typeof e !== 'string' && e.factory);

  const lines: string[] = [GENERATED_HEADER, ''];

  // --- imports ---
  if (mod === 'esm') {
    if (hasFactory) {
      lines.push("import { dirname } from 'node:path';");
      lines.push("import { fileURLToPath } from 'node:url';");
    }

    entries.forEach((entry, i) => {
      const { specifier, factory } = parseExtendsEntry(entry);
      const importName = factory ? `createConfig${i}` : `config${i}`;
      lines.push(`import ${importName} from '${specifier}';`);
    });

    lines.push('');

    if (hasFactory) {
      lines.push('const __dirname = dirname(fileURLToPath(import.meta.url));');
      lines.push('');
    }

    lines.push('export default [');
  } else {
    // CJS
    entries.forEach((entry, i) => {
      const { specifier, factory } = parseExtendsEntry(entry);
      const varName = factory ? `createConfig${i}` : `config${i}`;
      lines.push(`const ${varName} = require('${specifier}');`);
    });

    lines.push('');
    lines.push('module.exports = [');
  }

  // --- extends spreads ---
  for (let i = 0; i < entries.length; i++) {
    const { factory } = parseExtendsEntry(entries[i]);
    if (factory) {
      lines.push(`  ...createConfig${i}(__dirname),`);
    } else {
      lines.push(`  ...config${i},`);
    }
  }

  // --- ignores ---
  if (config.ignores && config.ignores.length > 0) {
    lines.push(`  { ignores: ${toInlineJs([...config.ignores])} },`);
  }

  // --- inline rules (when extends + rules are both set) ---
  if (config.rules && Object.keys(config.rules).length > 0) {
    lines.push(`  { rules: ${toInlineJs(config.rules)} },`);
  }

  // --- overrides ---
  if (config.overrides) {
    for (const override of config.overrides) {
      lines.push(
        `  { files: ${toInlineJs([...override.files])}, rules: ${toInlineJs(override.rules)} },`,
      );
    }
  }

  lines.push('];');
  lines.push('');

  const body = lines.join('\n');
  const hash = contentHash(body);

  return `${body}${HASH_PREFIX}${hash}\n`;
}

/** Compute SHA-256 hash of content (embedded in generated files as a human-readable change marker) */
function contentHash(content: string): string {
  return createHash('sha256').update(content).digest('hex').slice(0, 16);
}


/** Strip the hash comment line from generated file content for comparison */
function stripHash(content: string): string {
  const lines = content.trimEnd().split('\n');
  if (lines[lines.length - 1].startsWith(HASH_PREFIX)) {
    lines.pop();
  }
  return lines.join('\n').trimEnd();
}

/** Check if a file was generated by this adapter (has the generated header) */
function isGeneratedFile(content: string): boolean {
  return content.startsWith(GENERATED_HEADER);
}

/**
 * Create an ESLint adapter for Lodestar.
 * Implements ToolAdapter — runs ESLint via Node API and generates flat config for IDE.
 * @param config - ESLint-specific configuration (presets, rules, plugins, etc.)
 */
function eslintAdapter(config: EslintAdapterConfig): ToolAdapter<EslintAdapterConfig> {
  return {
    name: 'eslint',
    config,

    async check(rootDir: string, include: readonly string[]): Promise<readonly Violation[]> {
      const eslintModule = await import('eslint').catch(() => null);
      if (!eslintModule) {
        throw new Error(
          'ESLint is required for the eslint adapter. Install it: npm install -D eslint typescript-eslint',
        );
      }

      const flatConfig = await buildFlatConfig(config, rootDir);

      const eslint = new eslintModule.ESLint({
        overrideConfigFile: true,
        overrideConfig: flatConfig as never,
        cwd: rootDir,
        errorOnUnmatchedPattern: false,
      });

      const patterns = include.length > 0 ? [...include] : ['**/*.ts', '**/*.tsx'];
      const results = await eslint.lintFiles(patterns);

      const violations: Violation[] = [];
      for (const result of results) {
        const relativePath = result.filePath.startsWith(rootDir)
          ? result.filePath.slice(rootDir.length + 1)
          : result.filePath;

        for (const msg of result.messages) {
          violations.push({
            ruleId: `eslint/${msg.ruleId ?? 'unknown'}`,
            message: msg.message,
            severity: msg.severity === 2 ? 'error' : 'warn',
            location: { file: relativePath, line: msg.line, column: msg.column },
          });
        }
      }

      return violations;
    },

    async fix(rootDir: string, include: readonly string[]): Promise<void> {
      const eslintModule = await import('eslint').catch(() => null);
      if (!eslintModule) return;

      const flatConfig = await buildFlatConfig(config, rootDir);
      const eslint = new eslintModule.ESLint({
        overrideConfigFile: true,
        overrideConfig: flatConfig as never,
        cwd: rootDir,
        fix: true,
        errorOnUnmatchedPattern: false,
      });

      const patterns = include.length > 0 ? [...include] : ['**/*.ts', '**/*.tsx'];
      const results = await eslint.lintFiles(patterns);
      await eslintModule.ESLint.outputFixes(results);
    },

    async verifySetup(rootDir: string): Promise<readonly Violation[]> {
      const configPath = join(rootDir, 'eslint.config.js');
      const expected = await generateConfigFile(config, rootDir);
      const actual = await readFile(configPath, 'utf-8').catch(() => null);

      if (actual === null) {
        return [
          {
            ruleId: 'eslint/setup',
            message: 'Missing eslint.config.js — run `lodestar check --fix` to generate it.',
            severity: 'error',
            location: { file: 'eslint.config.js' },
            fix: {
              description: 'Create eslint.config.js from adapter config',
              apply: () => writeFile(configPath, expected, 'utf-8'),
            },
          },
        ];
      }

      // Only check drift for files we generated (has our header)
      if (isGeneratedFile(actual)) {
        const expectedBody = stripHash(expected);
        const actualBody = stripHash(actual);

        if (expectedBody !== actualBody) {
          return [
            {
              ruleId: 'eslint/setup',
              message:
                'eslint.config.js is out of sync with lodestar.config.ts — run `lodestar check --fix` to regenerate.',
              severity: 'error',
              location: { file: 'eslint.config.js' },
              fix: {
                description: 'Regenerate eslint.config.js from adapter config',
                apply: () => writeFile(configPath, expected, 'utf-8'),
              },
            },
          ];
        }
      }

      return [];
    },

    async generateConfig(): Promise<unknown[]> {
      return buildFlatConfig(config);
    },
  };
}

export { eslintAdapter, buildFlatConfig, generateConfigFile };
export type { EslintAdapterConfig, ExtendsEntry };
