import { describe, it, expect, afterEach } from 'vitest';
import { mkdir, mkdtemp, rm, writeFile, readFile } from 'node:fs/promises';
import { join } from 'node:path';
import { tmpdir } from 'node:os';
import { pathToFileURL } from 'node:url';
import { buildFlatConfig, eslintAdapter, generateConfigFile } from './adapter';
import type { EslintAdapterConfig } from './adapter';

describe('generateConfigFile', () => {
  const fixtures: string[] = [];

  afterEach(async () => {
    for (const dir of fixtures) {
      await rm(dir, { recursive: true, force: true });
    }
    fixtures.length = 0;
  });

  async function createTempDir(pkg?: Record<string, unknown>): Promise<string> {
    const dir = await mkdtemp(join(tmpdir(), 'eslint-adapter-test-'));
    fixtures.push(dir);
    if (pkg) {
      await writeFile(join(dir, 'package.json'), JSON.stringify(pkg), 'utf-8');
    }
    return dir;
  }

  it('generates ESM output for static extends', async () => {
    const dir = await createTempDir({ type: 'module' });
    const config: EslintAdapterConfig = {
      extends: '@repo/eslint-config/nest-eslint.config.js',
      ignores: ['generated/**', 'lodestar.config.ts'],
    };

    const result = await generateConfigFile(config, dir);

    expect(result).toContain('// @generated by Lodestar ESLint adapter');
    expect(result).toContain("import config0 from '@repo/eslint-config/nest-eslint.config.js'");
    expect(result).toContain('...config0,');
    expect(result).toContain('ignores');
    expect(result).toContain('export default [');
    expect(result).not.toContain('require');
    expect(result).not.toContain('fileURLToPath');
  });

  it('generates ESM output for factory extends', async () => {
    const dir = await createTempDir({ type: 'module' });
    const config: EslintAdapterConfig = {
      extends: { specifier: '@repo/eslint-config/react-app.config.js', factory: true },
      ignores: ['src/__generated__/**'],
    };

    const result = await generateConfigFile(config, dir);

    expect(result).toContain("import { dirname } from 'node:path'");
    expect(result).toContain("import { fileURLToPath } from 'node:url'");
    expect(result).toContain("import createConfig0 from '@repo/eslint-config/react-app.config.js'");
    expect(result).toContain('const __dirname = dirname(fileURLToPath(import.meta.url))');
    expect(result).toContain('...createConfig0(__dirname),');
    expect(result).toContain('export default [');
  });

  it('generates CJS output for static extends', async () => {
    const dir = await createTempDir({ type: 'commonjs' });
    const config: EslintAdapterConfig = {
      extends: '@repo/eslint-config/nest-eslint.config.js',
      ignores: ['generated/**'],
    };

    const result = await generateConfigFile(config, dir);

    expect(result).toContain(
      "const config0 = require('@repo/eslint-config/nest-eslint.config.js')",
    );
    expect(result).toContain('module.exports = [');
    expect(result).toContain('...config0,');
    expect(result).not.toContain('import ');
  });

  it('generates CJS output for factory extends', async () => {
    const dir = await createTempDir({ type: 'commonjs' });
    const config: EslintAdapterConfig = {
      extends: { specifier: '@repo/eslint-config/expo.config.js', factory: true },
      ignores: ['src/__generated__/**'],
    };

    const result = await generateConfigFile(config, dir);

    expect(result).toContain("const createConfig0 = require('@repo/eslint-config/expo.config.js')");
    expect(result).toContain('module.exports = [');
    expect(result).toContain('...createConfig0(__dirname),');
    // CJS uses __dirname natively, no fileURLToPath needed
    expect(result).not.toContain('fileURLToPath');
  });

  it('supports multiple extends entries', async () => {
    const dir = await createTempDir({ type: 'module' });
    const config: EslintAdapterConfig = {
      extends: [
        '@repo/eslint-config/base.config.js',
        { specifier: '@repo/eslint-config/react-app.config.js', factory: true },
      ],
    };

    const result = await generateConfigFile(config, dir);

    expect(result).toContain("import config0 from '@repo/eslint-config/base.config.js'");
    expect(result).toContain("import createConfig1 from '@repo/eslint-config/react-app.config.js'");
    expect(result).toContain('...config0,');
    expect(result).toContain('...createConfig1(__dirname),');
  });

  it('includes overrides in generated output', async () => {
    const dir = await createTempDir({ type: 'module' });
    const config: EslintAdapterConfig = {
      extends: '@repo/eslint-config/react-app.config.js',
      ignores: ['src/__generated__/**'],
      overrides: [{ files: ['src/platform/router/**'], rules: { 'no-restricted-imports': 'off' } }],
    };

    const result = await generateConfigFile(config, dir);

    expect(result).toContain('src/platform/router/**');
    expect(result).toContain('no-restricted-imports');
  });

  it('defaults to CJS when package.json has no type field', async () => {
    const dir = await createTempDir({ name: 'my-app' });

    const config: EslintAdapterConfig = {
      extends: '@repo/eslint-config/base.config.js',
    };

    const result = await generateConfigFile(config, dir);

    expect(result).toContain('module.exports = [');
    expect(result).toContain('require(');
  });

  it('defaults to CJS when package.json is missing', async () => {
    const dir = await createTempDir();

    const config: EslintAdapterConfig = {
      extends: '@repo/eslint-config/base.config.js',
    };

    const result = await generateConfigFile(config, dir);

    expect(result).toContain('module.exports = [');
  });

  it('respects explicit module option over package.json', async () => {
    const dir = await createTempDir({ type: 'commonjs' });
    const config: EslintAdapterConfig = {
      extends: '@repo/eslint-config/base.config.js',
      moduleFormat: 'esm',
    };

    const result = await generateConfigFile(config, dir);

    expect(result).toContain('export default [');
  });

  it('includes hash comment at end of file', async () => {
    const dir = await createTempDir({ type: 'module' });
    const config: EslintAdapterConfig = {
      extends: '@repo/eslint-config/base.config.js',
    };

    const result = await generateConfigFile(config, dir);

    const lines = result.trimEnd().split('\n');
    const lastLine = lines[lines.length - 1];
    expect(lastLine).toMatch(/^\/\/ @lodestar-hash [a-f0-9]{16}$/);
  });

  it('inlines rules when extends and rules are both set', async () => {
    const dir = await createTempDir({ type: 'module' });
    const config: EslintAdapterConfig = {
      extends: '@repo/eslint-config/base.config.js',
      rules: { '@typescript-eslint/no-unused-vars': 'error', 'no-console': 'warn' },
    };

    const result = await generateConfigFile(config, dir);

    expect(result).toContain("import config0 from '@repo/eslint-config/base.config.js'");
    expect(result).toContain('"@typescript-eslint/no-unused-vars"');
    expect(result).toContain('"no-console"');
    expect(result).toContain('rules');
  });

  it('throws when extends and presets are both set', async () => {
    const dir = await createTempDir({ type: 'module' });
    const config: EslintAdapterConfig = {
      extends: '@repo/eslint-config/base.config.js',
      presets: ['strict'],
    };

    await expect(generateConfigFile(config, dir)).rejects.toThrow('Cannot use `presets`');
  });

  it('throws when extends and plugins are both set', async () => {
    const dir = await createTempDir({ type: 'module' });
    const config: EslintAdapterConfig = {
      extends: '@repo/eslint-config/base.config.js',
      plugins: { unicorn: {} },
    };

    await expect(generateConfigFile(config, dir)).rejects.toThrow('Cannot use `plugins`');
  });

  it('generates no extends code when extends is not set', async () => {
    const dir = await createTempDir({ type: 'module' });
    const config: EslintAdapterConfig = {
      ignores: ['dist/**'],
    };

    const result = await generateConfigFile(config, dir);

    expect(result).toContain('export default [');
    expect(result).toContain('dist/**');
    expect(result).not.toContain('import config');
    expect(result).not.toContain('import createConfig');
  });
});

describe('eslintAdapter verifySetup()', () => {
  const fixtures: string[] = [];

  afterEach(async () => {
    for (const dir of fixtures) {
      await rm(dir, { recursive: true, force: true });
    }
    fixtures.length = 0;
  });

  async function createTempDir(pkg?: Record<string, unknown>): Promise<string> {
    const dir = await mkdtemp(join(tmpdir(), 'eslint-verify-test-'));
    fixtures.push(dir);
    if (pkg) {
      await writeFile(join(dir, 'package.json'), JSON.stringify(pkg), 'utf-8');
    }
    return dir;
  }

  it('reports violation when eslint.config.js is missing', async () => {
    const dir = await createTempDir({ type: 'module' });
    const adapter = eslintAdapter({
      extends: '@repo/eslint-config/base.config.js',
    });

    const violations = await adapter.verifySetup!(dir);

    expect(violations).toHaveLength(1);
    expect(violations[0].ruleId).toBe('eslint/setup');
    expect(violations[0].severity).toBe('error');
    expect(violations[0].fix).toBeDefined();
  });

  it('creates eslint.config.js via fix when missing', async () => {
    const dir = await createTempDir({ type: 'module' });
    const adapter = eslintAdapter({
      extends: '@repo/eslint-config/base.config.js',
      ignores: ['dist/**'],
    });

    const violations = await adapter.verifySetup!(dir);
    await violations[0].fix!.apply();

    const content = await readFile(join(dir, 'eslint.config.js'), 'utf-8');
    expect(content).toContain('// @generated by Lodestar ESLint adapter');
    expect(content).toContain("import config0 from '@repo/eslint-config/base.config.js'");

    // Should pass after fix
    const after = await adapter.verifySetup!(dir);
    expect(after).toHaveLength(0);
  });

  it('reports drift when generated file content changes', async () => {
    const dir = await createTempDir({ type: 'module' });
    const adapter = eslintAdapter({
      extends: '@repo/eslint-config/base.config.js',
    });

    // Create the expected file first
    const violations1 = await adapter.verifySetup!(dir);
    await violations1[0].fix!.apply();

    // Tamper with it (but keep the generated header)
    const content = await readFile(join(dir, 'eslint.config.js'), 'utf-8');
    const tampered = content.replace('base.config.js', 'other.config.js');
    await writeFile(join(dir, 'eslint.config.js'), tampered, 'utf-8');

    const violations2 = await adapter.verifySetup!(dir);
    expect(violations2).toHaveLength(1);
    expect(violations2[0].message).toContain('out of sync');
  });

  it('does not report drift for non-generated files', async () => {
    const dir = await createTempDir({ type: 'module' });
    const adapter = eslintAdapter({
      extends: '@repo/eslint-config/base.config.js',
    });

    // Write a user-managed eslint.config.js (no generated header)
    await writeFile(join(dir, 'eslint.config.js'), 'export default [{ rules: {} }];\n', 'utf-8');

    const violations = await adapter.verifySetup!(dir);
    expect(violations).toHaveLength(0);
  });
});

describe('buildFlatConfig', () => {
  const fixtures: string[] = [];

  afterEach(async () => {
    for (const dir of fixtures) {
      await rm(dir, { recursive: true, force: true });
    }
    fixtures.length = 0;
  });

  async function createTempDir(): Promise<string> {
    const dir = await mkdtemp(join(tmpdir(), 'eslint-buildflat-test-'));
    fixtures.push(dir);
    return dir;
  }

  async function writeFixture(dir: string, name: string, source: string): Promise<string> {
    const filePath = join(dir, name);
    await writeFile(filePath, source, 'utf-8');
    return pathToFileURL(filePath).href;
  }

  it('resolves static extends into the flat config at runtime', async () => {
    const dir = await createTempDir();
    const specifier = await writeFixture(
      dir,
      'static.mjs',
      `export default [
        { files: ['**/*.ts', '**/*.tsx'], rules: { 'no-fixture-rule': 'error' } },
      ];\n`,
    );

    const result = await buildFlatConfig({ extends: specifier }, dir);

    // The fixture block should be spread into the resulting config.
    expect(result).toEqual(
      expect.arrayContaining([
        { files: ['**/*.ts', '**/*.tsx'], rules: { 'no-fixture-rule': 'error' } },
      ]),
    );
  });

  it('skips @eslint/js recommended when extends is provided', async () => {
    const dir = await createTempDir();
    const specifier = await writeFixture(
      dir,
      'empty.mjs',
      'export default [{ files: ["**/*.ts"], rules: {} }];\n',
    );

    // Resolve the same object the adapter would pick up, then assert reference equality.
    // If @eslint/js cannot be resolved in the test env, this import throws and the test
    // fails loudly — preferable to a silently-passing object-shape probe.
    const eslintJs = (await import('@eslint/js')).default;
    const recommended = eslintJs.configs.recommended;

    const withoutExtends = await buildFlatConfig({});
    const withExtends = await buildFlatConfig({ extends: specifier }, dir);

    expect(withoutExtends).toContain(recommended);
    expect(withExtends).not.toContain(recommended);
  });

  it('invokes factory extends with rootDir', async () => {
    const dir = await createTempDir();
    const specifier = await writeFixture(
      dir,
      'factory.mjs',
      `export default (rootDir) => [
        { files: ['**/*.ts'], rules: { 'factory-saw-root': rootDir } },
      ];\n`,
    );

    const result = await buildFlatConfig({ extends: { specifier, factory: true } }, dir);

    const block = result.find(
      (b): b is { files: string[]; rules: { 'factory-saw-root': string } } =>
        typeof b === 'object' &&
        b !== null &&
        'rules' in b &&
        typeof (b as { rules?: Record<string, unknown> }).rules === 'object' &&
        (b as { rules: Record<string, unknown> }).rules !== null &&
        'factory-saw-root' in (b as { rules: Record<string, unknown> }).rules,
    );

    expect(block).toBeDefined();
    expect(block!.rules['factory-saw-root']).toBe(dir);
  });

  it('throws when a factory extends is declared but the module is not a function', async () => {
    const dir = await createTempDir();
    const specifier = await writeFixture(
      dir,
      'not-a-factory.mjs',
      'export default [{ rules: {} }];\n',
    );

    await expect(buildFlatConfig({ extends: { specifier, factory: true } }, dir)).rejects.toThrow(
      /factory/,
    );
  });

  it('throws a clear error when extends specifier cannot be loaded', async () => {
    await expect(
      buildFlatConfig({ extends: '@this-package/definitely-does-not-exist' }, '/tmp'),
    ).rejects.toThrow(/Failed to load ESLint config/);
  });

  it('check() reports violations defined by extends (regression for issue #31)', async () => {
    // End-to-end regression test: before the fix, extends was ignored by check(),
    // so no `files` glob matched any real file and `lintFiles` returned no results.
    // After the fix, a rule declared in the extended config should flag a real violation.
    const dir = await createTempDir();

    // Source file that violates `no-var`.
    await writeFile(join(dir, 'index.ts'), 'var answer = 42;\nconsole.log(answer);\n', 'utf-8');

    // Shared config fixture: globs `**/*.ts` and errors on `no-var`.
    const specifier = await writeFixture(
      dir,
      'shared.mjs',
      `export default [
        { files: ['**/*.ts'], rules: { 'no-var': 'error' } },
      ];\n`,
    );

    const adapter = eslintAdapter({ extends: specifier });
    const violations = await adapter.check!(dir, []);

    expect(violations.length).toBeGreaterThan(0);
    expect(violations.some((v) => v.ruleId === 'eslint/no-var')).toBe(true);
  });

  it('composes extends with overrides and ignores in the correct order', async () => {
    const dir = await createTempDir();
    const specifier = await writeFixture(
      dir,
      'multi.mjs',
      `export default [
        { files: ['**/*.ts'], rules: { 'from-extends': 'error' } },
      ];\n`,
    );

    const result = await buildFlatConfig(
      {
        extends: specifier,
        ignores: ['dist/**'],
        overrides: [{ files: ['**/root.tsx'], rules: { 'from-override': 'off' } }],
      },
      dir,
    );

    // ignores block first, then extends blocks, then override block.
    expect(result[0]).toEqual({ ignores: ['dist/**'] });
    const lastBlock = result[result.length - 1] as {
      files: string[];
      rules: Record<string, unknown>;
    };
    expect(lastBlock.files).toEqual(['**/root.tsx']);
    expect(lastBlock.rules).toEqual({ 'from-override': 'off' });
    expect(result).toEqual(
      expect.arrayContaining([{ files: ['**/*.ts'], rules: { 'from-extends': 'error' } }]),
    );
  });
});

describe('ESLint runtime resolution (regression for issue #34)', () => {
  const fixtures: string[] = [];

  afterEach(async () => {
    for (const dir of fixtures) {
      await rm(dir, { recursive: true, force: true });
    }
    fixtures.length = 0;
  });

  async function createTempDir(): Promise<string> {
    const dir = await mkdtemp(join(tmpdir(), 'eslint-resolve-test-'));
    fixtures.push(dir);
    return dir;
  }

  /**
   * Install a fake ESLint module at `<dir>/node_modules/eslint` so that
   * `createRequire(<dir>/package.json).resolve('eslint')` finds *this* copy
   * before any adapter-local one. The module body is plain ESM; use placeholders
   * like `__LINT_FILES_BODY__` to customize per-test behavior.
   */
  async function installFakeEslint(
    dir: string,
    opts: { version: string; lintFilesBody: string },
  ): Promise<void> {
    const pkgDir = join(dir, 'node_modules', 'eslint');
    await mkdir(pkgDir, { recursive: true });
    await writeFile(
      join(pkgDir, 'package.json'),
      JSON.stringify({
        name: 'eslint',
        version: opts.version,
        main: 'index.js',
        type: 'module',
      }),
      'utf-8',
    );
    await writeFile(
      join(pkgDir, 'index.js'),
      `export class ESLint {
         constructor(options) { this.options = options; }
         async lintFiles(patterns) { ${opts.lintFilesBody} }
         static async outputFixes() {}
       }
       export const Linter = { version: ${JSON.stringify(opts.version)} };
      `,
      'utf-8',
    );
  }

  it('prefers ESLint resolved from the user project rootDir', async () => {
    const dir = await createTempDir();
    await installFakeEslint(dir, {
      version: '9.32.0',
      lintFilesBody: `return [{
        filePath: 'fake.ts',
        messages: [{
          ruleId: 'from-project-eslint',
          message: 'marker from project-local eslint',
          severity: 2,
          line: 1,
          column: 1,
        }],
      }];`,
    });

    // An extends specifier is required so buildFlatConfig has something to load,
    // but the fake ESLint ignores the config — lintFiles returns a canned result.
    const specifier = pathToFileURL(join(dir, 'cfg.mjs')).href;
    await writeFile(join(dir, 'cfg.mjs'), 'export default [{ rules: {} }];\n', 'utf-8');

    const adapter = eslintAdapter({ extends: specifier });
    const violations = await adapter.check!(dir, []);

    // If the adapter picked up the real (adapter-local) ESLint, this rule id
    // would not appear. Finding it proves the project-local copy was used.
    expect(violations.some((v) => v.ruleId === 'eslint/from-project-eslint')).toBe(true);
  });

  it('augments scopeManager.addGlobals errors with a version-skew hint', async () => {
    const dir = await createTempDir();
    await installFakeEslint(dir, {
      version: '10.2.0',
      lintFilesBody: `throw new TypeError('scopeManager.addGlobals is not a function');`,
    });

    const specifier = pathToFileURL(join(dir, 'cfg.mjs')).href;
    await writeFile(join(dir, 'cfg.mjs'), 'export default [{ rules: {} }];\n', 'utf-8');

    const adapter = eslintAdapter({ extends: specifier });
    let caught: Error | null = null;
    try {
      await adapter.check!(dir, []);
    } catch (err) {
      caught = err as Error;
    }

    expect(caught).not.toBeNull();
    expect(caught!.message).toContain('scopeManager.addGlobals is not a function');
    // Skew-aware guidance — issue #34 workaround recipes.
    expect(caught!.message).toMatch(/pnpm[^]*overrides/);
    expect(caught!.message).toMatch(/10\.2\.0/); // resolved Linter.version surfaces
    expect((caught as { cause?: unknown }).cause).toBeInstanceOf(Error);
  });

  it('leaves non-skew errors untouched', async () => {
    const dir = await createTempDir();
    await installFakeEslint(dir, {
      version: '9.32.0',
      lintFilesBody: `throw new Error('some unrelated failure');`,
    });

    const specifier = pathToFileURL(join(dir, 'cfg.mjs')).href;
    await writeFile(join(dir, 'cfg.mjs'), 'export default [{ rules: {} }];\n', 'utf-8');

    const adapter = eslintAdapter({ extends: specifier });
    await expect(adapter.check!(dir, [])).rejects.toThrow(/^some unrelated failure$/);
  });
});
